name: main
on:
  push:
    tags:
      - 'v*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Meta
      id: shell-vars
      run: |
        nim_ver=$(curl -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/nim-lang/Nim/tags | jq -r '.[].name' | sort -rV | head -n 1)
        alpine_ver=$(./scripts/tags.sh "library/alpine")
        tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "::set-output name=NIM_VER::$nim_ver"
        echo "::set-output name=ALPINE_VER::$alpine_ver"
        echo "::set-output name=TAG::$tag"
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nim:${{ steps.shell-vars.outputs.TAG }}
        build-args: |
            ALPINE_VER=${{ steps.shell-vars.outputs.ALPINE_VER }}
            VERSION=${{ steps.shell-vars.outputs.NIM_VER }}