name: Build and deploy Nim action
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Docker Meta
      id: shell-vars
      run: echo '::set-output image=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)'
    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        REF: ${{ github.ref }}
        USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
      with:
        context: ./docker
        file: ./docker/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: ${{ steps.shell-vars.outputs.image.TAG }}